### ISSUE TITLE
Fix travis-ci build

### ISSUE THREAD

**Issue by davidmc24** [commercehub-oss/clouseau#4]
It looks like there's an incompatibility between the SSL certificate for JCenter and Gradle in Java 7.  From my research, there are a few possible workarounds:

* Drop Java 7 from `.travis.yml`
* Stop using HTTPS for accessing JCenter (`jcenter()` -> `jcenter { url "http://jcenter.bintray.com/" }`)
* Stop using JCenter (replace with `mavenCentral()`)
* Upgrade Gradle

I'm willing to try any of these fixes, but wanted to get your feedback before doing so.

**Comment by mhurne** [comment]
Closing, as this project is now deprecated.
